In [48]:
from sklearn.datasets import fetch_california_housing

In [49]:
dataset = fetch_california_housing()

In [50]:
dataset

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [51]:
print(dataset.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per ce

In [52]:
dataset.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [53]:
dataset.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [54]:
import pandas as pd

In [55]:
df = pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [56]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [57]:
df['Price']=dataset.target

In [58]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  Price  
0    -122.23  4.526  
1    -122.22  3.585  
2    -122.24  3.521  
3    -122.25  3.413  
4    -122.25  3.422

In [59]:
df.describe()

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude         Price  
count  20640.000000  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704      2.068558  
std       10.386050      2.135952      2.003532      1.153956  
min        0.692308     32.540000   -124.350000      0.149990  
25%        2.429741     33.930000   -121.800000      1.196000  
50%        2.818116     34.260000   -118.490000      1.797000  
75%        3.282261     37.710000   -118.010000      2.647250  
max     1243.333333     41.950000   -114.310000      5.000010

In [60]:
df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
Price         0
dtype: int64

In [61]:
#divide the dataset into independent and dependent
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [62]:
# divide the dataset into train and test
from sklearn.model_selection import train_test_split

x_train , x_test, y_train, y_test = train_test_split(
    x,y, test_size=0.33, random_state=42
)

In [63]:
x_train.shape,x_test.shape

((13828, 8), (6812, 8))

In [64]:
x.shape

(20640, 8)

In [65]:
# 3. Feature Scaling -- Standardization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [66]:
scaler.fit(x_train)

StandardScaler()

In [67]:
scaler.transform(x_train)

array([[-1.52169954, -0.75868455, -0.91813082, ..., -0.04014979,
        -0.78315293,  0.65090402],
       [ 0.18205382,  0.3523991 ,  0.30748451, ..., -0.05943619,
         0.8475975 , -1.31911678],
       [-0.17232772,  1.06666717, -0.25107784, ...,  0.09515433,
        -0.87218816,  0.66087881],
       ...,
       [-0.49518065,  0.59048846, -0.59192622, ...,  0.01608523,
        -0.75972261,  0.60103008],
       [ 0.96816708, -1.07613702,  0.39144665, ...,  0.0039722 ,
         0.90383028, -1.18445713],
       [-0.68377427,  1.86029835, -0.83041358, ..., -0.08065717,
         0.9928655 , -1.41387727]])

In [68]:
x_train=scaler.fit_transform(x_train)

In [69]:
x_train

array([[-1.52169954, -0.75868455, -0.91813082, ..., -0.04014979,
        -0.78315293,  0.65090402],
       [ 0.18205382,  0.3523991 ,  0.30748451, ..., -0.05943619,
         0.8475975 , -1.31911678],
       [-0.17232772,  1.06666717, -0.25107784, ...,  0.09515433,
        -0.87218816,  0.66087881],
       ...,
       [-0.49518065,  0.59048846, -0.59192622, ...,  0.01608523,
        -0.75972261,  0.60103008],
       [ 0.96816708, -1.07613702,  0.39144665, ...,  0.0039722 ,
         0.90383028, -1.18445713],
       [-0.68377427,  1.86029835, -0.83041358, ..., -0.08065717,
         0.9928655 , -1.41387727]])

In [70]:
x_test=scaler.transform(x_test)

In [86]:
from sklearn.linear_model import LinearRegression
regression= LinearRegression()
regression.fit(x_train,y_train)

LinearRegression()

In [87]:
regression.intercept_

2.0666362048018536

In [88]:
regression.coef_

array([ 8.46603472e-01,  1.20333548e-01, -2.98800785e-01,  3.47243173e-01,
       -8.81413334e-05, -4.17242067e-02, -8.94420371e-01, -8.70401317e-01])

In [89]:
# prediction
y_predict = regression.predict(x_test)

In [92]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
mse = mean_squared_error(y_test,y_predict)
mae =mean_absolute_error(y_test,y_predict)
np.sqrt(mse)


0.7327814505957737

In [119]:
# Acuracy R-Squared and  adjusted R-Squared
from sklearn.metrics import r2_score
r2score=r2_score(y_test,y_predict)
r2score

-2.5448582275933163e-05

In [121]:
# Display adjusted R-squared
adjustedR2score = 1 - (1 - r2score) * (len(y) - 1) / (len(y) - x.shape[1] - 1)
adjustedR2score

-0.0004132244335997015

In [122]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=20.0) # alpha parameter Ridge(alpha=)
ridge.fit(x_train,y_train)

Ridge(alpha=20.0)

In [123]:
y_predict= ridge.predict(x_test)

In [124]:
mse = mean_squared_error(y_test,y_predict)
mae =mean_absolute_error(y_test,y_predict)
print(np.sqrt(mse), mse, mae)

0.7325068291565449 0.5365662547609755 0.5295269970529026


In [125]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=20.0)
lasso.fit(x_train,y_train)


Lasso(alpha=20.0)

In [126]:
y_predict = lasso.predict(x_test)

In [127]:
mse = mean_squared_error(y_test,y_predict)
mae =mean_absolute_error(y_test,y_predict)
print(np.sqrt(mse), mse, mae)

1.15439409553007 1.3326257277946882 0.9126511897647483


In [128]:
from sklearn.linear_model import ElasticNet
elasticnet = ElasticNet(alpha=20.0)
elasticnet.fit(x_train,y_train)

ElasticNet(alpha=20.0)

In [129]:
y_predict = elasticnet.predict(x_test)

In [130]:
mse = mean_squared_error(y_test,y_predict)
mae =mean_absolute_error(y_test,y_predict)
print(np.sqrt(mse), mse, mae)

1.15439409553007 1.3326257277946882 0.9126511897647483


In [132]:
r2score

-2.5448582275933163e-05

In [133]:
adjustedR2score

-0.0004132244335997015